services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=codu_db'
      - 'POSTGRES_USER=my_user'
      - 'POSTGRES_PASSWORD=pass123'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: